[tox]
envlist = py310,py311
skipsdist = true

[testenv]
deps =
    -rrequirements.txt
commands =
    pytest --cov=src --cov-report=term --cov-report=html tests/

[testenv:mutmut]
deps =
    -rrequirements.txt
commands =
    mutmut run --paths-to-mutate src/
    mutmut results