[tox]
minversion = 4.0
envlist = py311,py312
skipsdist = True

[testenv]
deps =
    pytest
    pytest-cov
    pytest-xdist
    pytest-mock
commands =
    pytest --cov=src --cov-report=term --cov-report=html tests/