CREATE DATABASE IF NOT EXISTS MyProjectDB;
USE MyProjectDB;
-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 13:45:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Читатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Читатели` (
  `idЧитателя` INT NOT NULL,
  `ФИО` VARCHAR(150) NULL,
  `Телефон` VARCHAR(20) NULL,
  `Адрес` VARCHAR(45) NULL,
  `Дата_регистрации` DATE NULL,
  PRIMARY KEY (`idЧитателя`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Книги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Книги` (
  `idКниги` INT NOT NULL,
  `isbn` VARCHAR(20) NULL,
  `Название` VARCHAR(200) NULL,
  `Автор` VARCHAR(100) NULL,
  `Год` INT NULL,
  `Количество_экземпляров` INT NULL,
  PRIMARY KEY (`idКниги`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Выдача книг`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Выдача книг` (
  `id_выдачи` INT NOT NULL,
  `id_книги` INT NULL,
  `id_читателя` INT NULL,
  `Дата_выдачи` DATE NULL,
  `Дата_возврата_план` DATE NULL,
  `Дата_возврата_факт` DATE NULL,
  `Статус` VARCHAR(20) NULL,
  `Книги_idКниги` INT NOT NULL,
  `Читатели_idЧитателя` INT NOT NULL,
  PRIMARY KEY (`id_выдачи`, `Книги_idКниги`, `Читатели_idЧитателя`),
  UNIQUE INDEX `id_книги_UNIQUE` (`id_книги` ASC) VISIBLE,
  UNIQUE INDEX `id_читателя_UNIQUE` (`id_читателя` ASC) VISIBLE,
  INDEX `fk_Выдача книг_Книги_idx` (`Книги_idКниги` ASC) VISIBLE,
  INDEX `fk_Выдача книг_Читатели1_idx` (`Читатели_idЧитателя` ASC) VISIBLE,
  CONSTRAINT `fk_Выдача книг_Книги`
    FOREIGN KEY (`Книги_idКниги`)
    REFERENCES `mydb`.`Книги` (`idКниги`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Выдача книг_Читатели1`
    FOREIGN KEY (`Читатели_idЧитателя`)
    REFERENCES `mydb`.`Читатели` (`idЧитателя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Штрафы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Штрафы` (
  `id` INT NOT NULL,
  `id_выдачи` INT NULL,
  `Причина` TEXT NULL,
  `Сумма` DECIMAL(10,2) NULL,
  `Оплачен` TINYINT NULL,
  `Выдача книг_id_выдачи` INT NOT NULL,
  `Выдача книг_Книги_idКниги` INT NOT NULL,
  `Выдача книг_Читатели_idЧитателя` INT NOT NULL,
  PRIMARY KEY (`id`, `Выдача книг_id_выдачи`, `Выдача книг_Книги_idКниги`, `Выдача книг_Читатели_idЧитателя`),
  UNIQUE INDEX `id_выдачи_UNIQUE` (`id_выдачи` ASC) VISIBLE,
  INDEX `fk_Штрафы_Выдача книг1_idx` (`Выдача книг_id_выдачи` ASC, `Выдача книг_Книги_idКниги` ASC, `Выдача книг_Читатели_idЧитателя` ASC) VISIBLE,
  CONSTRAINT `fk_Штрафы_Выдача книг1`
    FOREIGN KEY (`Выдача книг_id_выдачи` , `Выдача книг_Книги_idКниги` , `Выдача книг_Читатели_idЧитателя`)
    REFERENCES `mydb`.`Выдача книг` (`id_выдачи` , `Книги_idКниги` , `Читатели_idЧитателя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
